jobs:
  - job: Windows
    pool:
      vmImage: windows-latest
    steps:
      - powershell: |
          .\O365EmailAddressPolicy.Tests.ps1
        displayName: "Run Windows - PowerShell 5.1"
      - pwsh: |
          .\O365EmailAddressPolicy.Tests.ps1
        displayName: "Run Windows - PowerShell 7"
  - job: Ubuntu
    pool:
      vmImage: ubuntu-latest
    steps:
      - pwsh: |
          .\O365EmailAddressPolicy.Tests.ps1
        displayName: "Run Ubuntu - PowerShell 7"
  - job: MacOS
    pool:
      vmImage: macOS-latest
    steps:
      - pwsh: |
          .\O365EmailAddressPolicy.Tests.ps1
        displayName: "Run MacOs - PowerShell 7"
